import { Report, Animal, Profile, PredictedHotspot, StewardshipZone, Intervention, DashboardStats } from '@/types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'user-1',
    full_name: 'Fatima Zahra Benali',
    phone: '+212661234567',
    role: 'volunteer',
    city: 'Casablanca',
    avatar_url: null,
    fcm_token: null,
    reputation_score: 340,
    is_available: true,
    location: { lat: 33.5731, lng: -7.5898 },
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    full_name: 'Youssef El Mansouri',
    phone: '+212662345678',
    role: 'steward',
    city: 'Rabat',
    avatar_url: null,
    fcm_token: null,
    reputation_score: 210,
    is_available: true,
    location: { lat: 34.0209, lng: -6.8416 },
    created_at: '2024-02-10T08:00:00Z',
  },
  {
    id: 'user-3',
    full_name: 'Khadija Alaoui',
    phone: '+212663456789',
    role: 'vet',
    city: 'Marrakech',
    avatar_url: null,
    fcm_token: null,
    reputation_score: 580,
    is_available: false,
    location: { lat: 31.6295, lng: -7.9811 },
    created_at: '2023-11-05T14:00:00Z',
  },
];

export const MOCK_ANIMALS: Animal[] = [
  {
    id: 'animal-1',
    species: 'dog',
    estimated_age: '2 ans',
    gender: 'male',
    distinctive_marks: 'Tache blanche sur l\'oreille gauche',
    nickname: 'Zidane',
    status: 'at_large',
    first_seen_at: '2024-03-01T09:00:00Z',
    last_seen_at: '2024-11-20T14:30:00Z',
    sighting_count: 7,
    story_public: true,
    created_at: '2024-03-01T09:00:00Z',
  },
  {
    id: 'animal-2',
    species: 'cat',
    estimated_age: '1 an',
    gender: 'female',
    distinctive_marks: 'Robe tricolore, queue tronquée',
    nickname: 'Nadia',
    status: 'fostered',
    first_seen_at: '2024-06-15T11:00:00Z',
    last_seen_at: '2024-11-18T10:00:00Z',
    sighting_count: 3,
    story_public: true,
    created_at: '2024-06-15T11:00:00Z',
  },
  {
    id: 'animal-3',
    species: 'dog',
    estimated_age: '4 ans',
    gender: 'female',
    distinctive_marks: 'Pelage roux, boiterie patte droite',
    nickname: 'Sahara',
    status: 'adopted',
    first_seen_at: '2024-01-10T08:00:00Z',
    last_seen_at: '2024-10-05T16:00:00Z',
    sighting_count: 12,
    story_public: true,
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'animal-4',
    species: 'cat',
    estimated_age: '3 mois',
    gender: 'unknown',
    distinctive_marks: 'Chaton noir, yeux bleus',
    nickname: 'Nuit',
    status: 'rescued',
    first_seen_at: '2024-11-15T20:00:00Z',
    last_seen_at: '2024-11-22T09:00:00Z',
    sighting_count: 2,
    story_public: false,
    created_at: '2024-11-15T20:00:00Z',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'report-1',
    reporter_id: 'user-1',
    animal_id: 'animal-1',
    title: 'Chien blessé Hay Mohammadi',
    description: 'Chien avec patte antérieure blessée, saigne. Refuse de se déplacer.',
    image_urls: [],
    video_url: null,
    location: { lat: 33.5620, lng: -7.6250 },
    city: 'Casablanca',
    district: 'Hay Mohammadi',
    urgency: 'high',
    status: 'assigned',
    ai_urgency_score: 0.87,
    ai_animal_type: 'dog',
    assigned_to: 'user-2',
    created_at: '2024-11-22T14:30:00Z',
    updated_at: '2024-11-22T14:45:00Z',
    reporter: MOCK_PROFILES[0],
    animal: MOCK_ANIMALS[0],
  },
  {
    id: 'report-2',
    reporter_id: 'user-2',
    animal_id: 'animal-2',
    title: 'Chatte errante Médina Fès',
    description: 'Chatte avec des chatons dans la ruelle. Semble affamée.',
    image_urls: [],
    video_url: null,
    location: { lat: 34.0617, lng: -5.0073 },
    city: 'Fès',
    district: 'Médina',
    urgency: 'medium',
    status: 'in_progress',
    ai_urgency_score: 0.62,
    ai_animal_type: 'cat',
    assigned_to: 'user-3',
    created_at: '2024-11-22T10:00:00Z',
    updated_at: '2024-11-22T10:30:00Z',
    reporter: MOCK_PROFILES[1],
    animal: MOCK_ANIMALS[1],
  },
  {
    id: 'report-3',
    reporter_id: 'user-3',
    animal_id: null,
    title: 'Chien abandonné Guéliz',
    description: 'Chien attaché à un poteau depuis 2 jours, personne ne s\'en occupe.',
    image_urls: [],
    video_url: null,
    location: { lat: 31.6400, lng: -8.0100 },
    city: 'Marrakech',
    district: 'Guéliz',
    urgency: 'critical',
    status: 'new',
    ai_urgency_score: 0.95,
    ai_animal_type: 'dog',
    assigned_to: null,
    created_at: '2024-11-22T16:00:00Z',
    updated_at: '2024-11-22T16:00:00Z',
    reporter: MOCK_PROFILES[2],
  },
  {
    id: 'report-4',
    reporter_id: 'user-1',
    animal_id: 'animal-4',
    title: 'Chaton abandonné Agdal',
    description: 'Chaton trouvé seul, très jeune. Pleure sans arrêt.',
    image_urls: [],
    video_url: null,
    location: { lat: 34.0050, lng: -6.8550 },
    city: 'Rabat',
    district: 'Agdal',
    urgency: 'high',
    status: 'rescued',
    ai_urgency_score: 0.78,
    ai_animal_type: 'cat',
    assigned_to: 'user-2',
    created_at: '2024-11-21T09:00:00Z',
    updated_at: '2024-11-22T08:00:00Z',
    reporter: MOCK_PROFILES[0],
    animal: MOCK_ANIMALS[3],
  },
  {
    id: 'report-5',
    reporter_id: 'user-2',
    animal_id: null,
    title: 'Chien errant Corniche',
    description: 'Chien errant sur la corniche, semble perdu mais pas blessé.',
    image_urls: [],
    video_url: null,
    location: { lat: 33.6050, lng: -7.6320 },
    city: 'Casablanca',
    district: 'Ain Diab',
    urgency: 'low',
    status: 'closed',
    ai_urgency_score: 0.35,
    ai_animal_type: 'dog',
    assigned_to: null,
    created_at: '2024-11-20T12:00:00Z',
    updated_at: '2024-11-21T10:00:00Z',
    reporter: MOCK_PROFILES[1],
  },
];

export const MOCK_HOTSPOTS: PredictedHotspot[] = [
  {
    id: 'hotspot-1',
    city: 'Casablanca',
    district: 'Hay Hassani',
    center: { lat: 33.5400, lng: -7.6500 },
    radius_meters: 1200,
    risk_score: 0.91,
    trigger_reason: 'Post-Aïd Al-Adha — pic historique d\'abandons',
    predicted_for: '2024-11-25',
    created_at: '2024-11-22T06:00:00Z',
  },
  {
    id: 'hotspot-2',
    city: 'Marrakech',
    district: 'Médina',
    center: { lat: 31.6300, lng: -7.9800 },
    radius_meters: 800,
    risk_score: 0.75,
    trigger_reason: 'Saison touristique — afflux animaux errants',
    predicted_for: '2024-11-26',
    created_at: '2024-11-22T06:00:00Z',
  },
  {
    id: 'hotspot-3',
    city: 'Fès',
    district: 'Ville Nouvelle',
    center: { lat: 34.0350, lng: -5.0000 },
    radius_meters: 600,
    risk_score: 0.62,
    trigger_reason: 'Pic de fin de mois — abandons économiques',
    predicted_for: '2024-11-28',
    created_at: '2024-11-22T06:00:00Z',
  },
  {
    id: 'hotspot-4',
    city: 'Rabat',
    district: 'Hay Riad',
    center: { lat: 33.9700, lng: -6.8700 },
    radius_meters: 700,
    risk_score: 0.48,
    trigger_reason: 'Tendance hebdomadaire — fin de semaine',
    predicted_for: '2024-11-29',
    created_at: '2024-11-22T06:00:00Z',
  },
];

export const MOCK_ZONES: StewardshipZone[] = [
  {
    id: 'zone-1',
    steward_id: 'user-2',
    name: 'Zone Bab Doukkala',
    center: { lat: 31.6340, lng: -8.0020 },
    radius_meters: 500,
    description: 'Quartier historique — surveillance active depuis mars 2024',
    is_active: true,
    total_cases: 24,
    resolved_cases: 21,
    created_at: '2024-03-01T08:00:00Z',
    steward: MOCK_PROFILES[1],
  },
  {
    id: 'zone-2',
    steward_id: 'user-1',
    name: 'Secteur Hay Riad',
    center: { lat: 33.9750, lng: -6.8600 },
    radius_meters: 500,
    description: 'Zone résidentielle — café le Palmier, gardien actif',
    is_active: true,
    total_cases: 11,
    resolved_cases: 9,
    created_at: '2024-05-15T09:00:00Z',
    steward: MOCK_PROFILES[0],
  },
];

export const MOCK_STATS: DashboardStats = {
  total_reports: 1247,
  active_reports: 43,
  resolved_reports: 1089,
  total_volunteers: 312,
  active_volunteers: 87,
  total_animals: 834,
  adopted_animals: 156,
  avg_response_time_minutes: 18,
  reports_by_urgency: {
    critical: 89,
    high: 312,
    medium: 547,
    low: 299,
  },
  reports_by_city: [
    { city: 'Casablanca', count: 412 },
    { city: 'Rabat', count: 198 },
    { city: 'Marrakech', count: 187 },
    { city: 'Fès', count: 143 },
    { city: 'Tanger', count: 112 },
    { city: 'Agadir', count: 98 },
    { city: 'Autres', count: 97 },
  ],
  monthly_trend: [
    { month: 'Jan', reports: 78, resolved: 71 },
    { month: 'Fév', reports: 92, resolved: 85 },
    { month: 'Mar', reports: 105, resolved: 96 },
    { month: 'Avr', reports: 89, resolved: 83 },
    { month: 'Mai', reports: 118, resolved: 108 },
    { month: 'Jun', reports: 134, resolved: 121 },
    { month: 'Jul', reports: 156, resolved: 139 },
    { month: 'Aoû', reports: 143, resolved: 127 },
    { month: 'Sep', reports: 98, resolved: 91 },
    { month: 'Oct', reports: 112, resolved: 104 },
    { month: 'Nov', reports: 122, resolved: 64 },
  ],
};
